/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

import ToDoApp.Controllers.ProjectController;
import ToDoApp.Models.Project;
import ToDoApp.Util.ConnectionFactory;
import java.sql.Connection;
import java.util.List;

public class App {

    public static void main(String[] args) {
        
        ProjectController projectController = new ProjectController();
        
        Project project = new Project();
       
        project.setId(1);
        project.setName("Novo nome do Projeto");
        project.setDescription("Descrição");
        
        projectController.update(project);
        
        List <Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
    }
}
